config/routes.rb
Rails.application.routes.draw do
  root 'exhibits#index'

  resources :types

  get '/assets/upload/:exhibit_id' => 'assets#asset_upload'
  post '/save-asset' => 'assets#save_asset'
  resources :assets

  resources :exhibits
  
  resources :users

  get 'validate_email/:v' => 'users#validate_email'
  get 'users/:id/:message' => 'users#show'

  resources :sessions, only: [:new, :create, :destroy]

  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete

  get '/error/no-access' => 'error#no_access'
  get '/error/email-auth' => 'error#email_auth'
  get '/error/not-signed-in' => 'error#not_signed_in'

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Listing types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>