config/routes.rb
Rails.application.routes.draw do
  root 'exhibits#index'

  resources :types

  get '/assets/upload/:exhibit_id' => 'assets#asset_upload'
  post '/save-asset' => 'assets#save_asset'
  resources :assets

  resources :exhibits
  
  resources :users

  get 'validate_email/:v' => 'users#validate_email'
  get 'users/:id/:message' => 'users#show'

  resources :sessions, only: [:new, :create, :destroy]

  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete

  get '/error/no-access' => 'error#no_access'
  get '/error/email-auth' => 'error#email_auth'
  get '/error/not-signed-in' => 'error#not_signed_in'

end

app/models/exhibit.rb
class Exhibit < ActiveRecord::Base
  belongs_to :user
  has_many :assets, dependent: :destroy
end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
  before_action :set_exhibit, only: [:show, :edit, :update, :destroy]

  # GET /exhibits
  # GET /exhibits.json
  def index
    @exhibits = Exhibit.where('private = ?', false)
  end

  # GET /exhibits/1
  # GET /exhibits/1.json
  def show
  end

  # GET /exhibits/new
  def new
    @exhibit = Exhibit.new
    @types = Type.all

    respond_to do |format|
        format.html { render :new, :layout => 'new_exhibit' }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
    end
  end

  # GET /exhibits/1/edit
  def edit
  end

  # POST /exhibits
  # POST /exhibits.json
  def create
    @exhibit = Exhibit.new(exhibit_params)
    current_user.exhibits << @exhibit

    respond_to do |format|
      if @exhibit.save
        format.html { redirect_to '/assets/upload/' + @exhibit.id, notice: 'Exhibit was successfully created.' }
        format.json { render :show, status: :created, location: @exhibit }
      else
        format.html { render :new }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibits/1
  # PATCH/PUT /exhibits/1.json
  def update
    respond_to do |format|
      if @exhibit.update(exhibit_params)
        format.html { redirect_to @exhibit, notice: 'Exhibit was successfully updated.' }
        format.json { render :show, status: :ok, location: @exhibit }
      else
        format.html { render :edit }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibits/1
  # DELETE /exhibits/1.json
  def destroy
    @exhibit.destroy
    respond_to do |format|
      format.html { redirect_to exhibits_url, notice: 'Exhibit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibit
      @exhibit = Exhibit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exhibit_params
      params.require(:exhibit).permit(:user_id, :type_id, :name, :url, :private)
    end
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/views/exhibits/_form.html.erb
<%= form_for(@exhibit) do |f| %>
  <% if @exhibit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exhibit.errors.count, "error") %> prohibited this exhibit from being saved:</h2>

      <ul>
      <% @exhibit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_id %><br>
    <%= collection_select(:exhibit, :type_id, @types, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :private %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exhibits/edit.html.erb
<h1>Editing exhibit</h1>

<%= render 'form' %>

<%= link_to 'Show', @exhibit %> |
<%= link_to 'Back', exhibits_path %>

app/views/exhibits/index.html.erb
<h1>Listing exhibits</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Type</th>
      <th>Url</th>
      <th>Private</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exhibits.each do |exhibit| %>
      <tr>
        <td><%= exhibit.user_id %></td>
        <td><%= exhibit.type_id %></td>
        <td><%= exhibit.url %></td>
        <td><%= exhibit.private %></td>
        <td><%= link_to 'Show', exhibit %></td>
        <td><%= link_to 'Edit', edit_exhibit_path(exhibit) %></td>
        <td><%= link_to 'Destroy', exhibit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exhibit', new_exhibit_path %>

app/views/exhibits/new.html.erb
<h1>New exhibit</h1>

<%= render 'form' %>

<%= link_to 'Back', exhibits_path %>

app/views/exhibits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @exhibit.user_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @exhibit.type_id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @exhibit.url %>
</p>

<p>
  <strong>Private:</strong>
  <%= @exhibit.private %>
</p>

<%= link_to 'Edit', edit_exhibit_path(@exhibit) %> |
<%= link_to 'Back', exhibits_path %>