config/routes.rb
Rails.application.routes.draw do
  root 'exhibits#index'

  resources :types

  get '/assets/upload/:exhibit_id' => 'assets#asset_upload'
  post '/save-asset' => 'assets#save_asset'
  resources :assets

  resources :exhibits
  
  resources :users

  get 'validate_email/:v' => 'users#validate_email'
  get 'users/:id/:message' => 'users#show'

  resources :sessions, only: [:new, :create, :destroy]

  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete

  get '/error/no-access' => 'error#no_access'
  get '/error/email-auth' => 'error#email_auth'
  get '/error/not-signed-in' => 'error#not_signed_in'

end

app/models/user.rb
require 'base64'
class User < ActiveRecord::Base
  has_secure_password

  has_many :exhibits, dependent: :destroy

  validates :username, presence: true, length: { maximum: 50 },
            uniqueness: {case_sensitive: false}

  validates :email, presence: true, 
            uniqueness: {case_sensitive: false}

  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true


  before_validation :create_auth_id, :on => :create
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  def send_auth_email  user
    params = {"id" => user.id, "auth_id" => user.auth_id}.to_json
    params_encoded = Base64.encode64(params)
    # EmailAuthMailer.send_auth_email(user, params_encoded).deliver
  end

  protected

  def create_auth_id
    begin
       self.auth_id = SecureRandom.urlsafe_base64(nil, false)
    end while User.where(auth_id: auth_id).exists?
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    puts @user.id
    puts Exhibit.all.inspect
    @my_exhibits = current_user.exhibits
    raise @my_exhibits.inspect
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :password_digest, :auth_id, :admin, :remember_token)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_header.html.erb
<div class="header">
  <% if signed_in? %>
    <%= link_to "Sign out", signout_path, method: "delete" %>
    <a href="#" class="my-account-trigger">My account</a>   
  <% else %>
    <a href="#" class="login-trigger">Login</a>

    <div class="login-form hidden">
      <%= form_for(:session, url: sessions_path) do |f| %>

          <%= f.label :email %>
          <%= f.text_field :email %>

          <%= f.label :password %>
          <%= f.password_field :password %>

          <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Auth</th>
      <th>Admin</th>
      <th>Remember token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.auth_id %></td>
        <td><%= user.admin %></td>
        <td><%= user.remember_token %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Auth:</strong>
  <%= @user.auth_id %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong>Remember token:</strong>
  <%= @user.remember_token %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>