config/routes.rb
Rails.application.routes.draw do
  root 'exhibits#index'

  resources :types

  get '/assets/upload/:exhibit_id' => 'assets#asset_upload'
  post '/save-asset' => 'assets#save_asset'
  resources :assets

  resources :exhibits
  
  resources :users

  get 'validate_email/:v' => 'users#validate_email'
  get 'users/:id/:message' => 'users#show'

  resources :sessions, only: [:new, :create, :destroy]

  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete

  get '/error/no-access' => 'error#no_access'
  get '/error/email-auth' => 'error#email_auth'
  get '/error/not-signed-in' => 'error#not_signed_in'

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :exhibit
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]
  before_action :require_exhibit_belongs_to_current_user, only: [:asset_upload]
  skip_before_filter :verify_authenticity_token, only: [:save_asset]

  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(asset_params)

    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render :show, status: :created, location: @asset }
      else
        format.html { render :new }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to assets_url, notice: 'Asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def asset_upload
    @exhibit = Exhibit.find(params['exhibit_id'])
    @asset = Asset.new
  end

  def save_asset
    resp = Hash.new
    path = Rails.root.to_s + '/public/test'
    uploaded = params[:file]
    Dir.chdir(path)
    file = File.new(uploaded.original_filename, "w+")
    file.write(uploaded.read)
    file.close
    # if !name.empty? && !data.empty?
    #   push = Push.new
    #   resp = push.to_s3 name, data
    # end
    respond_to do |format|
      format.json { render json: resp, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:url, :order)
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= form_for(@asset) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :url %>
  <%= f.hidden_field :order %>
  <%= hidden_field_tag :name, nil, :id => 'name' %>
  <%= hidden_field_tag :data, nil, :id => 'data' %>
<% end %>

app/views/assets/asset_upload.html.erb
<% if !@exhibit.nil? %>
  <a href="#" id="manual-file-trigger">Select files to upload</a>
  <input type="file" id="manual-file" multiple/>
  <div id="drop-container"><div id="drop-container-text">Or you can just drag and drop your files here.</div></div>
  <ul id="images"></ul>
  <div id="upload-dialogue">
    <div class="message">All files are selected for upload by default. Click any images that you wish to deselect.</div>
    <a href="#" id="upload-trigger">Upload selected files</a>
  </div>
  <script>
    var exhibitId = <%= @exhibit.id %>;
  </script>
<% else %>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<h1>Listing assets</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.url %></td>
        <td><%= asset.order %></td>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/new.html.erb
<h1>New asset</h1>

<%= render 'form' %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @asset.url %>
</p>

<p>
  <strong>Order:</strong>
  <%= @asset.order %>
</p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>